from openmm import CustomNonbondedForce, CustomBondForce, NonbondedForce
from openmm.unit import nanometer
import xml.etree.ElementTree as ET
from collections import defaultdict, deque

def add_slater_custom(system, topology, xml_path, cutoff=1.2*nanometer, scales=None, exclusions=None, covalent_correction=True):
    """Attach PhyNEO Slater short-range channels as a CustomNonbondedForce.

    ``scales`` contains exchange, es, pol, disp, dhf and B.  A scales the
    corresponding channel energy; B scales the Slater exponent (B -> B*s).
    The damping C6/C8/C10 terms are scaled with ``disp``.  This path is a
    compatibility bridge for the ADMPPme OpenMM plugin, which has no native
    SlaterForce classes; single-pair differential tests are required before
    production use.
    """
    scales = {"exchange": 1.0, "es": 1.0, "pol": 1.0, "disp": 1.0,
              "dhf": 1.0, "B": 1.0, **(scales or {})}
    root=ET.parse(xml_path).getroot()
    fields=['Aex','Bex','Aes','Bes','Apol','Bpol','Adhf','Bdhf','Asdisp','Bsdisp','Bdisp','C6','C8','C10','Bqq','Qqq']
    types={x:{} for x in fields}
    for tag,fa,fb in [('SlaterExForce','Aex','Bex'),('SlaterSrEsForce','Aes','Bes'),('SlaterSrPolForce','Apol','Bpol'),('SlaterDhfForce','Adhf','Bdhf'),('SlaterSrDispForce','Asdisp','Bsdisp')]:
        e=root.find(tag)
        if e is not None:
            for a in e.findall('Atom'):
                t=a.get('type'); types[fa][t]=float(a.get('A',0)); types[fb][t]=float(a.get('B',0))
    for a in root.find('SlaterDampingForce').findall('Atom'):
        t=a.get('type')
        types['Bdisp'][t]=float(a.attrib['B'])
        for x in ['C6','C8','C10']: types[x][t]=float(a.attrib[x])
    for a in root.find('QqTtDampingForce').findall('Atom'):
        t=a.get('type'); types['Bqq'][t]=float(a.get('B',0)); types['Qqq'][t]=float(a.get('Q',0))
    names=fields
    def pol(a,b):
        x=f"(sqrt(scale_B*scale_B*{b}1*{b}2)*r)"
        return f"({x}^2/3+{x}+1)"
    ex=f"scale_exchange*Aex1*Aex2*{pol('Aex','Bex')}*exp(-scale_B*sqrt(Bex1*Bex2)*r)"
    es=f"scale_es*Aes1*Aes2*{pol('Aes','Bes')}*exp(-scale_B*sqrt(Bes1*Bes2)*r)"
    ep=f"scale_pol*Apol1*Apol2*{pol('Apol','Bpol')}*exp(-scale_B*sqrt(Bpol1*Bpol2)*r)"
    eh=f"scale_dhf*Adhf1*Adhf2*{pol('Adhf','Bdhf')}*exp(-scale_B*sqrt(Bdhf1*Bdhf2)*r)"
    ed=f"scale_disp*Asdisp1*Asdisp2*{pol('Asdisp','Bsdisp')}*exp(-scale_B*sqrt(Bsdisp1*Bsdisp2)*r)"
    b="scale_B*sqrt(Bdisp1*Bdisp2)"; x=f"({b}*r)"; z=f"({x}-(2*{x}^2+3*{x})/({x}^2+3*{x}+3))"
    f6=f"exp(-{z})*(1+{z}+{z}^2/2+{z}^3/6+{z}^4/24+{z}^5/120+{z}^6/720)"
    f8=f"({f6}+exp(-{z})*({z}^7/5040+{z}^8/40320))"
    f10=f"({f8}+exp(-{z})*({z}^9/362880+{z}^10/3628800))"
    disp=f"scale_disp*({f6}*sqrt(C61*C62)/(r^6)+{f8}*sqrt(C81*C82)/(r^8)+{f10}*sqrt(C101*C102)/(r^10))"
    qq="-1389.35455846*exp(-scale_B*sqrt(Bqq1*Bqq2)*r)*(1+scale_B*sqrt(Bqq1*Bqq2)*r)*Qqq1*Qqq2/(10*r)"
    # OpenMM requires every intermediate used by the energy expression to be
    # declared in its semicolon definition section.  The previous bridge
    # referenced f6/f8/f10 without attaching those definitions.
    expr=(f"{ex}-({es})-({ep})-({ed})-({eh})+({disp});"
          f"f10={f10};f8={f8};f6={f6};z={z};x={x};")
    f=CustomNonbondedForce(expr)
    for name in ("scale_exchange", "scale_es", "scale_pol", "scale_disp", "scale_dhf", "scale_B"):
        f.addGlobalParameter(name, float(scales[name.removeprefix("scale_")]))
    f.setNonbondedMethod(CustomNonbondedForce.CutoffPeriodic); f.setCutoffDistance(cutoff)
    for n in names: f.addPerParticleParameter(n)
    residue_map={(res.get('name'),a.get('name')):a.get('type') for res in root.find('Residues') for a in res.findall('Atom')}
    atoms = list(topology.atoms())
    for atom in atoms:
        t=residue_map[(atom.residue.name,atom.name)]; f.addParticle([types[n].get(t,0.) for n in names])
    # Reuse the exception list generated by the HMTFF force field.  The
    # ADMPPme/MPID plugin and OpenMM require every nonbonded-like force to
    # carry an identical exception list.  Reconstructing exclusions from
    # connected components (or from a guessed 1--4 rule) silently violates
    # this requirement for ring/long-chain molecules.
    excl = set(exclusions or ())
    if exclusions is None:
        for force in system.getForces():
            if isinstance(force, NonbondedForce):
                for k in range(force.getNumExceptions()):
                    i, j, *_ = force.getExceptionParameters(k)
                    excl.add((min(int(i), int(j)), max(int(i), int(j))))
                break
    for i,j in sorted(excl): f.addExclusion(i,j)
    # DMFF mScale12..mScale16 suppress covalent distances 1..5.  Keep the
    # native 1-4 exception identity shared with MPID and cancel only distances four and five
    # through a short-range CustomBondForce.
    adj = defaultdict(set)
    for bond in topology.bonds():
        adj[bond.atom1.index].add(bond.atom2.index)
        adj[bond.atom2.index].add(bond.atom1.index)
    suppressed = []
    for i in range(topology.getNumAtoms()):
        seen={i}; front={i}
        for _ in range(5):
            front={j for u in front for j in adj[u] if j not in seen}; seen |= front
        suppressed.extend((i,j) for j in seen if i<j and (i,j) not in excl)
    if covalent_correction and suppressed:
        corr_expr=(f"-({ex}-({es})-({ep})-({ed})-({eh})+({disp}));"
                   f"f10={f10};f8={f8};f6={f6};z={z};x={x};")
        for _a in ("ex","es","pol","dhf","disp"):
            corr_expr=corr_expr.replace(f"A{_a}1*A{_a}2", f"A{_a}")
            corr_expr=corr_expr.replace("Asdisp1*Asdisp2","Asdisp").replace("sqrt(scale_B*scale_B*Bsdisp1*Bsdisp2)","scale_B*Bsdisp")
            corr_expr=corr_expr.replace(f"sqrt(B{_a}1*B{_a}2)", f"B{_a}")
            corr_expr=corr_expr.replace(f"sqrt(scale_B*scale_B*B{_a}1*B{_a}2)", f"scale_B*B{_a}")
        corr_expr=corr_expr.replace("sqrt(Bdisp1*Bdisp2)","Bdisp").replace("Bsdisp1","Bsdisp").replace("Bsdisp2","Bsdisp")
        corr_expr=corr_expr.replace("sqrt(C61*C62)","sqrt(C6)").replace("sqrt(C81*C82)","sqrt(C8)").replace("sqrt(C101*C102)","sqrt(C10)")
        correction = CustomBondForce(corr_expr)
        for name in ("scale_exchange", "scale_es", "scale_pol", "scale_disp", "scale_dhf", "scale_B"):
            correction.addGlobalParameter(name, float(scales[name.removeprefix("scale_")]))
        bond_names=("Aex","Bex","Aes","Bes","Apol","Bpol","Adhf","Bdhf","Asdisp","Bsdisp","Bdisp","C6","C8","C10")
        for n in bond_names: correction.addPerBondParameter(n)
        for i,j in suppressed:
            ti=residue_map[(atoms[i].residue.name,atoms[i].name)]; tj=residue_map[(atoms[j].residue.name,atoms[j].name)]
            def prod(name): return types[name].get(ti,0)*types[name].get(tj,0)
            vals=[prod('Aex'),prod('Bex')**0.5,prod('Aes'),prod('Bes')**0.5,prod('Apol'),prod('Bpol')**0.5,prod('Adhf'),prod('Bdhf')**0.5,prod('Asdisp'),prod('Bsdisp')**0.5,prod('Bdisp')**0.5,prod('C6'),prod('C8'),prod('C10')]
            correction.addBond(i,j,vals)
        correction.setForceGroup(18); correction.setName("SlaterCovalentCorrection_PeriodicBond_%d" % len(suppressed)); system.addForce(correction)
    f.setName("SlaterCustomForce_1to4_plus_distance5_correction_%d" % len(suppressed))
    for i in reversed(range(system.getNumForces())):
        if isinstance(system.getForce(i), NonbondedForce):
            system.removeForce(i)
    system.addForce(f); return f,len(excl)
